package dtsquared.nwschoolsafewalk.database.schema;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "MARKER".
 */
@Entity
public class Marker {

    @Id
    private Long id;

    @NotNull
    private String name;
    private String latitude;
    private String longitude;
    private String geofencemaker;

    @Generated
    public Marker() {
    }

    public Marker(Long id) {
        this.id = id;
    }

    @Generated
    public Marker(Long id, String name, String latitude, String longitude, String geofencemaker) {
        this.id = id;
        this.name = name;
        this.latitude = latitude;
        this.longitude = longitude;
        this.geofencemaker = geofencemaker;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(@NotNull String name) {
        this.name = name;
    }

    public String getLatitude() {
        return latitude;
    }

    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    public String getLongitude() {
        return longitude;
    }

    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

    public String getGeofencemaker() {
        return geofencemaker;
    }

    public void setGeofencemaker(String geofencemaker) {
        this.geofencemaker = geofencemaker;
    }

}
